/* Automatically generated by './build/bin/build-entry.js' */
// 内部组件
import ArrowInputGroup from 'packages/arrow-input-group/index.js';
import Alert from 'packages/alert/index.js';

// 内部指令 这里的代码很乱，希望有机会能够更改
// import directives from './directives/index.js'
// import './utils/prototype.js'

// 第三方工具库
import _ from 'lodash'
import Plyr from 'plyr'

// 内部工具
import VueClipboard from 'vue-clipboard2'

// 样式文件
import 'plyr/dist/plyr.css'

import "./assets/iconfont/iconfont.js";
import "./assets/reset/index.scss";

const components = [
  ArrowInputGroup,
];

const utils = [
  Confirm,
  Alert,
  VueClipboard
]

const install = function(Vue, opts = {}) {
  
  Object.keys(directives).forEach(k => {
    Vue.directive(k, directives[k])
  });

  components.forEach(component => {
    Vue.component(component.name, component);
  });
  
  utils.forEach(util => {
    Vue.use(util);
  });

  Vue.prototype._ = _
};

window.Plyr = Plyr

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  ArrowInputGroup
};
